using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Extrato_API.Migrations
{
    /// <inheritdoc />
    public partial class AddLicaoConcluidaClean : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
                        migrationBuilder.Sql(@"DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'tb_licao_concluida'
    ) THEN
        CREATE TABLE tb_licao_concluida (
            id_licao_concluida integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id uuid NOT NULL,
            licao_id integer NOT NULL,
            concluido_em timestamp with time zone NOT NULL
        );
    END IF;
END
$$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
                        migrationBuilder.Sql(@"DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = 'tb_licao_concluida'
    ) THEN
        DROP TABLE tb_licao_concluida;
    END IF;
END
$$;");
        }
    }
}
