// <auto-generated />
using System;
using Extrato_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Extrato_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507072557_AddLicaoConcluidaClean")]
    partial class AddLicaoConcluidaClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Extrato_API.Models.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alternativa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer")
                        .HasColumnName("atividade_id");

                    b.Property<bool?>("Correta")
                        .HasColumnType("boolean")
                        .HasColumnName("correta");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.ToTable("tb_alternativa");
                });

            modelBuilder.Entity("Extrato_API.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_atividade");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dificuldade")
                        .HasColumnType("integer")
                        .HasColumnName("dificuldade");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enunciado");

                    b.Property<int>("LicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("licao_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<bool?>("ProvaFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("prova_final");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.ToTable("tb_atividade");
                });

            modelBuilder.Entity("Extrato_API.Models.EstatisticasUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciciosResolvidos")
                        .HasColumnType("integer");

                    b.Property<int>("LicoesConcluidas")
                        .HasColumnType("integer");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<int>("SequenciaDias")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EstatisticasUsuarios");
                });

            modelBuilder.Entity("Extrato_API.Models.Licao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_licao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer")
                        .HasColumnName("modulo_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("RecompensaXp")
                        .HasColumnType("integer")
                        .HasColumnName("recompensa_xp");

                    b.Property<string>("TextoConceito")
                        .HasColumnType("text")
                        .HasColumnName("texto_conceito");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("TituloConceito")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo_conceito");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("tb_licao");
                });

            modelBuilder.Entity("Extrato_API.Models.LicaoConcluida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_licao_concluida");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<int>("LicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("licao_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.ToTable("tb_licao_concluida");
                });

            modelBuilder.Entity("Extrato_API.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_modulo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("tb_modulo");
                });

            modelBuilder.Entity("Extrato_API.Models.Tentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tentativa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternativaEscolhidaId")
                        .HasColumnType("integer")
                        .HasColumnName("alternativa_escolhida_id");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("integer")
                        .HasColumnName("atividade_id");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean")
                        .HasColumnName("correta");

                    b.Property<Guid>("EstudanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("estudante_id");

                    b.Property<DateTime?>("TentadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tentado_em");

                    b.Property<int?>("XpGanho")
                        .HasColumnType("integer")
                        .HasColumnName("xp_ganho");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaEscolhidaId");

                    b.HasIndex("AtividadeId");

                    b.ToTable("tb_tentativa");
                });

            modelBuilder.Entity("Extrato_API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.ToTable("tb_usuario", (string)null);
                });

            modelBuilder.Entity("Extrato_API.Models.Alternativa", b =>
                {
                    b.HasOne("Extrato_API.Models.Atividade", "Atividade")
                        .WithMany("Alternativas")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("Extrato_API.Models.Atividade", b =>
                {
                    b.HasOne("Extrato_API.Models.Licao", "Licao")
                        .WithMany("Atividades")
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");
                });

            modelBuilder.Entity("Extrato_API.Models.Licao", b =>
                {
                    b.HasOne("Extrato_API.Models.Modulo", "Modulo")
                        .WithMany("Licoes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Extrato_API.Models.Tentativa", b =>
                {
                    b.HasOne("Extrato_API.Models.Alternativa", "AlternativaEscolhida")
                        .WithMany()
                        .HasForeignKey("AlternativaEscolhidaId");

                    b.HasOne("Extrato_API.Models.Atividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativaEscolhida");

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("Extrato_API.Models.Atividade", b =>
                {
                    b.Navigation("Alternativas");
                });

            modelBuilder.Entity("Extrato_API.Models.Licao", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("Extrato_API.Models.Modulo", b =>
                {
                    b.Navigation("Licoes");
                });
#pragma warning restore 612, 618
        }
    }
}
